# Default model configuration

input_dim: 30
seq_len: 30
max_h: 30
max_w: 30
d_model: 256
encoder_layers: 2
decoder_layers: 2
heads: 4
d_ff: 128
output_dim: 30
dropout_rate: 0.15 # General dropout for the model

context_encoder:
  d_model: 1024
  heads: 16
  dropout_rate: 0.12

encoder_dropout_rate: 0.61
decoder_dropout_rate: 0.12

lora:
  use_lora: false
  rank: 128
  in_features: 128 # Default, consider making this dynamic or more configurable if needed
  out_features: 128 # Default, consider making this dynamic or more configurable if needed

checkpoint_path: "/workspaces/JARC-Reactor/lightning_logs/checkpoints/model-step=step=40-val_loss=val_loss=1.7084.ckpt"
