site_name: Cultivation Documentation
# site_url: https://<your-github-username>.github.io/<repo-name>/
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
docs_dir: cultivation/docs
nav:
  - Home: index.md
  - 0 Introduction And Strategy:
    - Readme: 0_introduction_and_strategy/README.md
    - The Dao Of Cultivation A Founding Vision: 0_introduction_and_strategy/The_Dao_of_Cultivation_A_Founding_Vision.md
    - Archive:
      - Readme: 0_introduction_and_strategy/archive/README.md
      - Critique And Refinement: 0_introduction_and_strategy/archive/critique_and_refinement.md
      - Final Thoughts: 0_introduction_and_strategy/archive/final_thoughts.md
      - Potential Overview: 0_introduction_and_strategy/archive/potential_overview.md
      - Synergy Concept: 0_introduction_and_strategy/archive/synergy_concept.md
      - Systems Map And Market Cheatsheet: 0_introduction_and_strategy/archive/systems_map_and_market_cheatsheet.md
      - Ultimate Goals: 0_introduction_and_strategy/archive/ultimate_goals.md
    - Project Philosophy And Core Concepts: 0_introduction_and_strategy/project_philosophy_and_core_concepts.md
  - 1 Background Theory:
    - Readme: 1_background_theory/README.md
    - Domains Scope: 1_background_theory/domains_scope.md
    - Hyper Detailed Theoretical Outline: 1_background_theory/hyper_detailed_theoretical_outline.md
  - 2 Requirements And Specifications:
    - Readme: 2_requirements_and_specifications/README.md
    - Data Schemas:
      - Readme: 2_requirements_and_specifications/data_schemas/README.md
      - Strength Data Schemas: 2_requirements_and_specifications/data_schemas/strength_data_schemas.md
    - Flashcard System Spec: 2_requirements_and_specifications/flashcard_system_spec.md
    - Formal System:
      - Readme: 2_requirements_and_specifications/formal_system/README.md
      - Lean Guide: 2_requirements_and_specifications/formal_system/lean_guide.md
      - Lean Tools: 2_requirements_and_specifications/formal_system/lean_tools.md
      - Math Stack: 2_requirements_and_specifications/formal_system/math_stack.md
    - Functional Requirements: 2_requirements_and_specifications/functional_requirements.md
    - Non Functional Requirements: 2_requirements_and_specifications/non_functional_requirements.md
    - Task Master Integration Spec: 2_requirements_and_specifications/task_master_integration_spec.md
  - 3 Design And Architecture:
      - Readme: 3_design_and_architecture/README.md
      - Architecture Overview: 3_design_and_architecture/architecture_overview.md
      - Integrations:
          - Readme: 3_design_and_architecture/integrations/README.md
          - External Systems Analysis: 3_design_and_architecture/integrations/external_systems_analysis.md
      - Knowledge System:
          - Readme: 3_design_and_architecture/knowledge_system/README.md
          - Archive:
              - Flashcard Anki Addon Design: 3_design_and_architecture/knowledge_system/flashcard_anki_addon_design.md
          - Flashcard Self Assessment Design: 3_design_and_architecture/knowledge_system/flashcard_self_assessment_design.md
          - Knowledge Acquistion Analysis: 3_design_and_architecture/knowledge_system/knowledge_acquistion_analysis.md
          - Knowledge Creation And Validation: 3_design_and_architecture/knowledge_system/knowledge_creation_and_validation.md
          - Knowledge Measurement Theory: 3_design_and_architecture/knowledge_system/knowledge_measurement_theory.md
          - Literature System Overview: 3_design_and_architecture/knowledge_system/literature_system_overview.md
          - References:
              - Readme: 3_design_and_architecture/knowledge_system/references/README.md
              - Knowledge Creation And Validation Supporting Report: 3_design_and_architecture/knowledge_system/references/knowledge_creation_and_validation_supporting_report.md
          - User Experience Knowledge System: 3_design_and_architecture/knowledge_system/user_experience_knowledge_system.md
