
defaults:
  - schema: jarc_app # Explicitly load the main app schema
  - _self_          # Merge values from this file
  - model: default
  - training: default
  - optuna: default
  - logging: default
  - finetuning: default
  - metrics: default
  - scheduler: default
  - evaluation: default

# Global settings (can be overridden by group configs or command line)
use_best_params: false

# CUDA Optimizations (handled by a script, but can be toggled here if needed)
enable_cuda_optimizations: true
