name: CI - ARC System

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  arc_build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Go Task
        uses: actions/setup-task@v1
        with:
          version: latest 

      - name: Run ARC linters
        run: task arc:lint

      - name: Run ARC tests
        run: task arc:test
