on:
  push:
    paths: ['cultivation/data/processed/**']
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y jq bc
      - run: pip install -r requirements.txt
      - run: python cultivation/scripts/running/aggregate_weekly_runs.py
      - id: kpi
        run: |
          python - <<'PY'
          import os, pathlib, sys, json, pandas as pd
          w = pd.read_parquet('cultivation/data/weekly_metrics.parquet').tail(2)
          if len(w) < 2:
              print('::set-output name=insufficient_data::true')
              print(json.dumps({'ef': None, 'drift': None}))
              sys.exit(0)
          ef = (w['ef_mean'].iloc[-1] - w['ef_mean'].iloc[-2]) / w['ef_mean'].iloc[-2]
          drift = w['decoupling_mean'].iloc[-1]
          with open(os.environ["GITHUB_OUTPUT"], "a") as fh:
              fh.write(f"ef={ef}\n")
              fh.write(f"drift={drift}\n")
          print(json.dumps({'ef':ef, 'drift':drift}))
          PY
      - name: Fail if KPIs unmet
        if: ${{ (steps.kpi.outputs.ef | abs) < 0.05 || steps.kpi.outputs.ef < 0 || steps.kpi.outputs.drift > 0.07 }}
        run: exit 1
      - name: Insufficient data status
        if: steps.kpi.outputs.insufficient_data == 'true'
        run: echo "::warning ::Not enough weeks for KPI diff; skipping gate"