name: schedule-next-week

on:
  workflow_run:
    workflows: ["run-metrics"]
    types:
      - completed

jobs:
  advance-schedule:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run scheduler
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MODEL: ${{ secrets.MODEL }}
        run: |
          python cultivation/scripts/running/pid_scheduler.py
