name: Sync Habit Dash Wellness Data

on:
  schedule:
    # Runs daily at 5:00 AM UTC
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  sync-habitdash:
    runs-on: ubuntu-latest
    env:
      HABITDASH_API_KEY: ${{ secrets.HABITDASH_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Habit Dash sync script
        run: |
          export HABITDASH_API_KEY=${{ secrets.HABITDASH_API_KEY }}
          python cultivation/scripts/sync_habitdash.py

      - name: Commit and push updated wellness cache
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add cultivation/data/daily_wellness.parquet
          git commit -m 'chore: update daily_wellness.parquet [auto-sync]' || echo 'No changes to commit'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
